# WHAT IS NUMPY ?
 NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

To install numpy library:

pip install numpy 

## NUMPY ARRAY OPERATIONS


In [ ]:
## importing numpy library 

import numpy as np

In [82]:
## creating an array using numpy 

arr1=np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


In [ ]:
print(type(arr1))
print(arr1.shape) ## prints the shape of the array (6,) which means 1-D array with length 6 

<class 'numpy.ndarray'>
(6,)


In [90]:
arr2=np.array([1,2,3,4,5,6])
print(arr2)

## reshaping array 
arr2=arr2.reshape(2,3) ##reshapes the array into 2 rows and 3 coloumns 
print(arr2)
print(arr2.shape) ## 2 dimensional array wiht 2 rows and 3 coloumns 

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
## creating an array using arange 
## takes 3 arguments the starting element the last element(not included) and the increment value 
np.arange(0,10,2) 

array([0, 2, 4, 6, 8])

In [ ]:
## creating an array of ones takes 2 arguments (rows,columns)
np.ones((3,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
## Identity matrix 
## takes an argument of (no of rows) the diagnol elements will be one 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
arr=np.array([[1,2,3],[4,5,6]])
##arr shape
print(arr.shape)
##arr dimension
print(arr.ndim)
## number of elements
print(arr.size)
## arr data type
print(arr.dtype)
## arr item size in bytes
print(arr.itemsize)

(2, 3)
2
6
int64
8


# NUMPY VECTOR OPERATIONS

In [43]:
arr3=np.array([1,2,3,4,5])

In [40]:
arr4=np.array([6,7,8,9,10])

In [41]:
print(arr3)
print(arr4)
##ALL OPERATIONS ARE ELEMENT WISE 

##addition
print(arr3+arr4)
##subtraction
print(arr3-arr4)
##multiplication
print(arr3*arr4)
##divison
print(arr3/arr4)

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [44]:
##universal operations element wise

print(np.sqrt(arr3)) ##square root 

print(np.exp(arr3))  ##e^

print(np.sin(arr3))  ##sine of elements

print(np.log(arr3)) ##log of elements 


  


[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [50]:
##accessing elements 
## indexing is zero based means the element 1 is arr[0][0] element 2 is arr[0][1]

arr5=np.array([list(range(1,5)),list(range(5,9)),list(range(9,13))])
print(arr5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [53]:

print(arr5[0][0]) ##output 1

1


In [62]:
## accessing element 3,4 and 7,8 
arr5[0:2,2:] ## 0:2 selects the rows, 2: selects the coloums 


array([[3, 4],
       [7, 8]])

In [63]:
## accessing 6,7 and 10,11 
arr5[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [64]:
##modifying elements 

arr5[0][0]=2

print(arr5)

[[ 2  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Stastical Concepts


## NORMALISATION

In [66]:
## data to have mean of 0 and standard deviation of 1 
data =np.array([1,2,3,4,5])

mean=np.mean(data)
std_dev=np.std(data)

normalised_data=(data-mean)/std_dev 

print("Normalised data is", normalised_data)

Normalised data is [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [68]:
median=np.median(data)

variance=np.var(data)

print(f"mean of data is {mean}, standard deviation of data is {std_dev}, median of data is {median} and variance of data is {variance}")

mean of data is 3.0, standard deviation of data is 1.4142135623730951, median of data is 3.0 and variance of data is 2.0


## LOGICAL OPERATIONS 

In [74]:
print(data<5) ##gives true for values less than 5
print(data[data<5]) ##gives elements

[ True  True  True  True False]
[1 2 3 4]


In [78]:
print(data[(data<=2)|(data>=4)]) ##gives the elments whose value is less than equal to 2 which is 1 and 2 and elements whose values are greater than 4 which is 5 

## for logical operations we have to use '&' for 'and' operation '|' for 'or' operation. 

[1 2 4 5]
